Attempt2
neonestea/Lab1PromC- pull request #7
Opened 2023-05-28 13:28 UTC by neonestea

2023-05-31 11:31 UTC, namitmax requested changes

2023-05-31 11:31 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +        friend bool operator== (const reverseIterator& a, const reverseIterator& b) { return a.ptr_ == b.ptr_; };
так все же с неявным преобразованием что то надо делать или тут оно должно быть ?

2023-05-31 11:31 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +        iterator operator[](int n) const { //random Access, доступ О(1)
оператор квадратные скобки у итератора?

2023-05-31 11:31 UTC, namitmax commented on HW1_2/testsuite/libsrc/array/src/test.cpp
> +        auto i = *it;
зачем нужна переменная , вроде сразу можно сравнить ? В остальных случаях тоже

2023-06-01 20:16 UTC, namitmax requested changes

2023-06-01 20:16 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +        return !std::lexicographical_compare(data_, data_ + n1, other.data_, other.data_ + n2);
копипаста + это неправда , отрицание меньше это больше либо равно, добавьте тест

2023-06-01 20:16 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +        auto it = constIterator(&data_[0]);
зачем так сложно, можно же просто data[i]

2023-06-01 20:16 UTC, namitmax commented on HW1_2/include/array/array.hpp
>           if (*this == other || *this < other)
неоптимально, данную операцию можно выполнить за одно сравнение уже реализованное

2023-06-01 20:16 UTC, namitmax commented on HW1_2/include/array/array.hpp
>      bool operator>=(const MyArray& other) const
копипаста и опять же неоптимально

2023-06-01 20:16 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +            return *ptr_;
если разыменовать первый элемент там будет все ок, не получится ситуации при которой попробуем разыменовать end() ?

2023-06-02 08:05 UTC, neonestea commented on HW1_2/include/array/array.hpp
> +            return *ptr_;
Вообще, может. При проходе  for (auto it = arr.rbegin(), end = arr.rend(); it != end; ++it) не может, но, если взять auto it = arr.rend(), то может. Поправлю

2023-06-02 08:06 UTC, neonestea commented on HW1_2/include/array/array.hpp
> +        return !std::lexicographical_compare(data_, data_ + n1, other.data_, other.data_ + n2);
Тест был, проходит. Добавлю еще проверку на равенство

2023-06-02 08:09 UTC, neonestea commented on HW1_2/include/array/array.hpp
> +        auto it = constIterator(&data_[0]);
Поправила

2023-06-02 10:47 UTC, namitmax requested changes

2023-06-02 10:47 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +            return *ptr_;
насколько я помню в стандартной реализации reverse_iterator для получения итератора на первый элемент получает все же end() на вход, укажите в документации , что в вашей это end()-1 , либо поправьте реализацию

2023-06-02 10:47 UTC, namitmax commented on HW1_2/include/array/array.hpp
> +#include <iterator>
а зачем здесь данный include, что то не увидел с ходу?

2023-06-02 10:51 UTC, neonestea commented on HW1_2/include/array/array.hpp
> +#include <iterator>
не нужен

2023-06-02 10:52 UTC, neonestea commented on HW1_2/include/array/array.hpp
> +            return *ptr_;
напишу в документации

2023-06-02 10:56 UTC, namitmax commented
ок

2023-06-02 10:56 UTC, namitmax approved these changes

2023-06-02 10:57 UTC, merged